### ISSUE TITLE
Bun cannot find esbuild.js

### ISSUE THREAD

**Issue by LocalTrashCant** [d7omdev/keyvis#1]
Steps to reproduce:
Follow the instructions for manual installation. 
As ./install.sh cannot be run due to improper permissions, running chmod +x ./install.sh allows for it to run.
Running ./install.sh gives the output of:

$ bun run esbuild.js
error: FileNotFound while resolving package 'esbuild' from '/keyvis/esbuild.js'

Bun v1.1.33 (Linux x64 baseline)
error: script "build:app" exited with code 1
____________
bun --version: 1.1.33
Kernel Version: 6.11.4-arch1-1
Bun seems to be working properly.

**Comment by d7omdev** [comment]
Did you run `bun install` first? i think i forgot to add it to the install script..
Please run  `bun install` and try again and tell me how it went.

**Comment by LocalTrashCant** [comment]
It builds correctly now.

**Comment by LocalTrashCant** [comment]
Also don't forget to update the AUR version. 
Thanks for making.

**Comment by d7omdev** [comment]
The aur version was already correct that's why I didn't notice it, Thank you tho.
